FROM python:3.11-slim

ENV PYTHONUNBUFFERED=1

WORKDIR /app

COPY app/client/requirements.txt /tmp/requirements.txt
# FIX: Agregamos --default-timeout=1000 para evitar errores de red
RUN pip install --no-cache-dir --default-timeout=10000 -r /tmp/requirements.txt && rm /tmp/requirements.txt

COPY app/__init__.py /app/__init__.py
COPY app/common /app/common
COPY app/client /app/client

ENV PYTHONPATH=/app \
    DNS_SERVICE_HOST=dns_service \
    TARGET_SERVICE_NAME=server \
    TARGET_SERVICE_PORT=8000 \
    BROWSER_API_URL=http://localhost:8000

EXPOSE 8501

CMD ["streamlit", "run", "client/app.py", "--server.address=0.0.0.0", "--server.port=8501", "--server.headless=true", "--browser.gatherUsageStats=false"]
